trajectory_random_2:
  points_x: [0.0, 0.0, 5.0]
  points_y: [0.0, 3.0, 6.0]
  points_z: [0.0, 2.0, 3.0]
  times: [0.0, 6.0, 11.0]
  ros_rate: 20.0
  method: "minimum_snap"  # "cubic_spline", "natural_cubic_spline", "minimum_jerk", "minimum_snap"