circle_traj:
  circle_radius: 1.0      # Çemberin yarıçapı (metre cinsinden)
  z_height: 0.5           # Z ekseninde yükseklik (metre cinsinden)
  duration: 5.0          # Çemberin tamamlanma süresi (saniye)
  update_frequency: 20.0  # Frekans (Hz) ile güncelleme


  trajectory:
  points_x: [4.51, 2.47, 1.02, 0.00, 0.24, 1.50, 3.28, 5.62, 7.69, 9.12, 9.92, 10.00, 9.23, 7.78, 6.35, 4.48, 2.95, 1.75, 1.41, 2.07]
  points_y: [0.00, 0.86, 2.31, 4.67, 7.20, 9.06, 9.97, 10.00, 9.09, 7.55, 5.58, 3.78, 5.85, 7.47, 8.23, 8.39, 7.80, 6.28, 4.33, 2.28]
  points_z: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
  times: [0.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0, 27.0, 30.0, 33.0, 36.0, 39.0, 42.0, 45.0, 48.0, 51.0, 54.0, 57.0]
  ros_rate: 20.0
  return_to_start: true
  return_duration: 3.0
  method: "cubic_spline"  # "cubic_spline", "natural_cubic_spline", "minimum_jerk", "minimum_snap"