trajectory_random_2:
  points_x: [13.0, 16.0, 21.0, 25.0, 19.0]
  points_y: [11.0, 14.0, 10.0, 13.0, 18.0]
  points_z: [8.0, 6.0, 3.0, 3.0, 3.0]
  times: [0.0, 6.0, 11.0, 17.0, 22.0]
  ros_rate: 20.0
  method: "minimum_jerk"  # "cubic_spline", "natural_cubic_spline", "minimum_jerk", "minimum_snap"