trajectory_manager:
  active_trajectories: ["trajectory_random", "trajectory_random_2"]  # Birden fazla yörünge seçilebilir
  available_trajectory:
    - name: "trajectory_crescent"
      file: "trajectory_crescent.yaml"
    - name: "trajectory_random"
      file: "trajectory_random.yaml"
    - name: "trajectory_random_2"
      file: "trajectory_random_2.yaml"
    - name: "trajectory_hover"
      file: "trajectory_hover.yaml"
  return_to_start: true  
  return_duration: 8.0





