trajectory:
  points_x: [0.0, 0.0, 0.0, 5.0, 1.0, 13.0]
  points_y: [0.0, 0.0, 5.0, 5.0, -1.0, 7.0]
  points_z: [0.0, 4.0, 4.0, 4.0, 4.0, 8.0]
  times: [0.0, 6.0, 12.0, 18.0, 25.0, 35.0]
  ros_rate: 20.0
  return_to_start: true
  return_duration: 15.0
  method: "cubic_spline"  # "cubic_spline", "natural_cubic_spline", "minimum_jerk", "minimum_snap"








