clear all;
clc;

log_folder = '../log';
% ref_x_t(log_folder);
% ref_y_t(log_folder);
% ref_z_t(log_folder);
% ref_vel_x_t(log_folder);
% ref_vel_y_t(log_folder);
% ref_vel_z_t(log_folder);
% ref_acc_x_t(log_folder);
% ref_acc_y_t(log_folder);
% ref_acc_z_t(log_folder);
% % ref_plot_3d_xyz(log_folder);
% % actual_x_t(log_folder);
% % actual_y_t(log_folder);
% % actual_z_t(log_folder);
% % actual_plot_3d_xyz(log_folder);
% actual_vel_x_t(log_folder);
% actual_vel_y_t(log_folder);
% actual_vel_z_t(log_folder);
% actual_acc_x_t(log_folder);
% actual_acc_y_t(log_folder);
% actual_acc_z_t(log_folder);
% actual_angvel_x_t(log_folder);
% actual_angvel_y_t(log_folder);
% actual_angvel_z_t(log_folder);

plot_acc_x_y_z_t(log_folder);
plot_vel_x_y_z_t(log_folder);
plot_pos_x_y_z_t(log_folder);
plot_rpy_t(log_folder);
plot_rpy_t_degree(log_folder);